# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 424989b518179b087a5806c14273362551639eb35bae2a7a5ec0b7cbd759af6fffc3eddd8e3a7ba5924f1aa104f21748ffd29ae28ce9ca3811bdf622d800bd53

test:
  secret_key_base: a71a78edaafa1897ece9aef401586001040ae1088f0fabdf648d288b068b41058c05a34089daf0f0b85298b30d0d14cdee7afa7ed44c0378d24016abd074f0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
