# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b9cb1d4a067fdd0afb2159ee254bba07584e918af7e52ce2fc23a4ba40b26dca624eddce8ef4f7596a591809cdf2f838a638b4784e719f2a06bd8bd92d9511e

test:
  secret_key_base: 3ac38bea33a3df29db0408e1b4e6ae20a9d6d6ad1b6ba8e4da5ab20bf55ed6b3e343221beed6680d764afbbd102368ead288d13aa51b18dced9dd0ed66a6b619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
