# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4356004758979f400222ac4c8a840caf07295a8b13c243a96da38c3f1f5c290c8f801b0b5e092cb922afc11c792913054efdd1ecc599718530ff891e55fa0552

test:
  secret_key_base: e01a7a2b636c628772cb85fa94b30cf243af12195555470cae8bad87266e317d426a7dc68f7d0bca994f88e5f05af278f66ef44b2e78162fa0df2a50b73101e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
